version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.8
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Build content
          command: npm run task -- build:content
      - run:
          name: Build site
          command: npm run task -- build:site
      - save_cache:
          key: dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - content/dist/images
            - dist
  deploy:
    docker:
      - image: circleci/python:latest
    steps:
      - restore_cache:
          key: dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - aws-s3/sync:
          from: content/dist/images
          to: 's3://samkingco-imgix/design'
          arguments: '--acl public-read --cache-control max-age=31536000'
      - aws-s3/sync:
          from: dist
          to: 's3://samking.design'
          arguments: '--exclude "*.html" --exclude "*.json" --acl public-read --cache-control max-age=31536000'
          overwrite: true
      - aws-s3/sync:
          from: dist
          to: 's3://samking.design'
          arguments: '--exclude "*" --include "*.html" --include "*.json" --acl public-read --cache-control max-age=0'
          overwrite: true
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
