version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.8
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: build
          command: npm run task -- build:ci
      - aws-s3/sync:
          from: content/dist/images
          to: 's3://samkingco-imgix/design'
          arguments: '--acl public-read'
      - aws-s3/sync:
          from: dist
          to: 's3://samking.design'
          arguments: '--acl public-read'
